[tool.poetry]
name = "licence-plate-detection"
version = "0.1.0"
description = ""
authors = ["onoykomary"]
package-mode = false
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.15"

torch = "2.5.1" 
torchvision = "*"
numpy = "2.2.6"
albumentations = "^2.0.8"
scikit-image = "0.25.2"
segmentation_models_pytorch = "0.5.0"
timm = "1.0.20"
transformers = "^5.3.0"
tokenizers = "^0.22.2"
scikit-learn = "1.7.2"
pandas = "2.3.3"
matplotlib = "3.10.6"
seaborn = "0.13.2"
pillow = "11.3.0"
tqdm = "4.67.1"
ultralytics = ">=8.3.235,<9.0.0"
torchmetrics = ">=1.8.2,<2.0.0"
pycocotools = ">=2.0.10,<3.0.0"
jupyter = ">=1.1.1,<2.0.0"
ipykernel = ">=7.1.0,<8.0.0"
fiftyone = "^1.13.2"
onnx = "^1.20.1"
onnxruntime = "^1.24.2"
opencv-python = "^4.13.0.92"
fastapi = "^0.136.1"
uvicorn = "^0.46.0"
pydantic = "^2.13.3"
python-multipart = "^0.0.27"
pydantic-settings = "^2.14.0"
redis = "^7.4.0"
aiobotocore = "^3.7.0"
celery = "^5.6.3"
sqlalchemy = "^2.0.50"
psycopg2-binary = "^2.9.12"

[tool.poetry.group.dev.dependencies]
black = "24.10.0"
isort = ">=6.0,<7.0"
pre-commit = ">=4.5.0,<5.0.0"

